apiVersion: v1
kind: Service
metadata: 
  name: burger-service
  labels: 
    app: burger-service
spec: 
  type: NodePort
  ports: 
  - port: 3050
    nodePort: 30001
    targetPort: 80
    protocol: TCP
  selector: 
    component: burger