apiVersion: extensions/v1Beta1
kind: Deployment
metadata:
  name: hello-deploy
spec:
  replicas: 10
  minReadySeconds: 10
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata: 
      labels:
        app: hello-world
    spec:
      containers: 
      - name: hello-pod
        image: bhoopendra/jms-client:latests
        ports:
          containerPort: 8080